### ISSUE TITLE
add a 'analyze' or submit button under the compare field?

### ISSUE THREAD

**Issue by samfrons** [watson-developer-cloud/company-insights#11]
it's sort of odd to add companies then have to press the analyze button atop. 
thoughts?

**Comment by jeff-arn** [comment]
what if we switched it up to something more like this: http://h5c5ar.axshare.com/v1.html

**Comment by nfriedly** [comment]
Ohh, schnazzy. I'm going to have to remember that tool.

**Comment by nfriedly** [comment]
I think I'm going to pair this back a little bit to make sure it ships - the main change is that I'm only going to allow one competitor to compare against. I think I can have that much working in time for the sig event.

This + a little more polish should be all it takes to get this thing out the door.
