### ISSUE TITLE
How to access the app locally?

### ISSUE THREAD

**Issue by akankshajain** [watson-developer-cloud/company-insights#115]

**Comment by akankshajain** [comment]
On npm start I got :

> company-insights@1.0.0 start /root/hackathon/company-insights
> node app.js

api caching disabled, set REDIS_URL or config.services.redis to enable
company-insights v1.0.0 listening on port 8080

So my app is listening on port 8080 what url should I use to access this app? I tried http://159.8.150.177:8080/ but it says cannot GET /

**Comment by nfriedly** [comment]
Op, I think you need to run `npm run gulp-build` first, then `npm start`.

And, usually the URL is http://localhost:8080/ for local testing, although http://159.8.150.177:8080/ appears to be correct also.
