### ISSUE TITLE
Using paid account for caching

### ISSUE THREAD

**Issue by jeff-arn** [watson-developer-cloud/company-insights#131]
@nfriedly do we still need to run the redis account for this? Is there a free account we can move it over to?

**Comment by nfriedly** [comment]
The app is still using the redis account. It can work without it, but the performance is much better with it. I'm not aware of any free redis service, although there may be one somewhere. 

However, the paid service we're using is from [compose](https://www.compose.io/redis/) which is an IBM-owned company. So while it's not exactly free, we're really just shuffling money around withing IBM.  You might be able to get in touch with someone there and inquire about getting a free account, and in exchange we'll put instructions into the readme here for users to buy a paid account for their instance ;)

**Comment by nfriedly** [comment]
There we go, I added a few instructions on setting up redis and gave Compose a shout out at the end: https://github.com/watson-developer-cloud/company-insights/blob/master/README.md#redis-caching-layer
