### ISSUE TITLE
Change @dropbox text when you focus on the field

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/company-insights#14]
Is it easy to change that text when it "floats" above the field? If not, then maybe we should just put different text there from the start. (Actually, it probably shouldn't be @dropbox either way... maybe @ibmwatson ;)

**Comment by jeff-arn** [comment]
Yeah the wireframe skipped a step. The prefilled text should be something like "Enter a Twitter handle", that way when it raises up if it consistent with the next bar which says "Enter and add handle to compare". Thoughts?

**Comment by nfriedly** [comment]
Yea, I like that better.
