### ISSUE TITLE
add caching

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/company-insights#16]
The server should cache api results for at least 24 hours, especially for twitter which will both get more traffic and have limits that we can't control.

**Comment by nfriedly** [comment]
https://www.compose.io/redis/ would be a good option if we can get an account. https://console.ng.bluemix.net/catalog/data-cache/ is also a possibility, although there isn't any node.js library right now and the documentation seems a bit sparse.

**Comment by ghost** [comment]
https://github.com/watson-developer-cloud/company-insights/commit/26a5c911964cfaed56d09b82c4d1a65f7d0d1dce
