### ISSUE TITLE
URL for Presentation Monday

### ISSUE THREAD

**Issue by jeff-arn** [watson-developer-cloud/company-insights#19]
Is http://company-insights.mybluemix.net the URL that we want to use for tomorrow?

**Comment by nfriedly** [comment]
Yea, go ahead and use that one. I pushed out updates from the hotel last
night, and I can do the same tonight if anyone puts in updates today.

**Comment by jeff-arn** [comment]
Ok great. I tried it out and this will be great for Monday (although if anyone has updates go ahead). I'm going to use Spacex for the demo, interesting combination of lower sentiment (with news of recent crashes) but a high openness score (showing "behind the scenes" and "technical" news)
