### ISSUE TITLE
where does 'join the ecosystem' go? 

### ISSUE THREAD

**Issue by samfrons** [watson-developer-cloud/company-insights#6]

**Comment by nfriedly** [comment]
I think it should point to http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/ although the name doesn't make sense then.
@Repjarms: ?

**Comment by jeff-arn** [comment]
@nfriedly @samfrons the ecosystem link should go here: http://www.ibm.com/smarterplanet/us/en/ibmwatson/ecosystem.html

In some of the other materials for this launch we will be promoting the dev cloud but this piece is very specific trying to drive applications for the ecosystem.

**Comment by nfriedly** [comment]
(re-opening until we get it correct)
