### ISSUE TITLE
sentiment analysis

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/company-insights#9]
We'd like to add sentiment analysis of what other twitter users are saying about the company. Questions: 
- What does it look like?
- Do we want sentiment scores for every tweet that mentions the company, or a composite score for all recent tweets combined, or something else?

**Comment by nfriedly** [comment]
@Repjarms any thoughts on this?

**Comment by nfriedly** [comment]
I'm thinking maybe just a composite score of all recent tweets that we convert to a percentage (from AlchemyAPI's -1 to 1 scoring), and then mention how many recent tweets it's based off of and/or the timeframe of those tweets.

**Comment by jeff-arn** [comment]
@nfriedly I like the idea of the composite score, as showing sentiment by tweet will be too granular to show a trend IMO. and yes if we can show the count of tweets taken into the composite, or better yet the major outlier tweets that are boosting or dragging down the score, that would be great.

**Comment by jeff-arn** [comment]
@nfriedly perhaps its just a bar from -1 to 1 and it plots them (and their comparisons) somewhere on that bar. but ill defer to you guys on the best way to implement that.

**Comment by nfriedly** [comment]
Yea, I like that. A bar with the composite score for each company and the maybe a few outliers for your company.

**Comment by jeff-arn** [comment]
Sweet! That would be great

**Comment by nfriedly** [comment]
I have the UI cleaned up to show the sentiment for the main company now. In favor of having something ready to ship, I'm going to call this good enough for now and work on cleaning up other aspects of the app before trying to add sentiment for the competitors and/or individual tweets.

<img width="1022" alt="screen shot 2015-09-21 at 2 54 43 pm" src="https://cloud.githubusercontent.com/assets/114976/10001673/e9eb41f4-6070-11e5-9bc1-c6a7e96eef85.png">
